name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v30
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
        enable_kvm: true
        extra_nix_config: "system-features = nixos-test benchmark big-parallel kvm"
    - run: nix build
    - run: nix flake check
    - run: nix run .
